[project]
name = "semantic-endpointing"
description = "Demo showcasing semantic endpointing for voice agents"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.116.1",
    "torch>=2.7.1",
    "transformers>=4.53.3",
    "websockets>=15.0.1",
]
